# Generated by Django 3.2.4 on 2022-05-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='subscription',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
