# Generated by Django 3.2.4 on 2022-05-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anticipate', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiorder',
            name='cylinder',
            field=models.ManyToManyField(related_name='anti_cylinders', to='products.Product'),
        ),
    ]
