# Generated by Django 3.2.4 on 2022-05-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Product Type')),
                ('mass', models.CharField(db_index=True, max_length=6, unique=True, verbose_name='LPG Weight')),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('tare', models.CharField(db_index=True, max_length=6, null=True, unique=True, verbose_name='Tare Weight')),
                ('working', models.CharField(db_index=True, max_length=6, null=True, verbose_name='Working Pressure')),
                ('test', models.CharField(db_index=True, max_length=6, null=True, verbose_name='Test Pressure')),
                ('water', models.CharField(db_index=True, max_length=6, null=True, verbose_name='Water Capacity')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories_img/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder', models.CharField(max_length=30, null=True, verbose_name='Cylinder Id')),
                ('category', models.CharField(max_length=12, null=True)),
                ('outlet', models.CharField(max_length=30, null=True)),
                ('vendor_product_status', models.CharField(choices=[('Dispatched to Plant', 'Dispatched to Plant'), ('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Released Filled to QwikPartner', 'Released Filled to QwikPartner'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer')], max_length=30, null=True, verbose_name="QwikVendor's Remark")),
                ('partner_product_status', models.CharField(blank=True, choices=[('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Dispatched to Plant', 'Dispatched to Plant'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Dispatched Filled to QwikCustomer', 'Dispatched Filled to QwikCustomer'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet')], max_length=35, null=True, verbose_name="QwikPartner's Remark")),
                ('partner_confirm', models.BooleanField(blank=True, null=True, verbose_name="QwikPartner's Confirmation")),
                ('vendor_confirm', models.BooleanField(blank=True, default=False, null=True, verbose_name="QwikVendor's Confirmation")),
                ('who', models.CharField(blank=True, max_length=8, null=True)),
                ('who_2', models.CharField(blank=True, max_length=9, null=True)),
                ('who2', models.CharField(blank=True, max_length=8, null=True)),
                ('who2_2', models.CharField(blank=True, max_length=9, null=True)),
                ('who3', models.CharField(blank=True, max_length=8, null=True)),
                ('who3_2', models.CharField(blank=True, max_length=9, null=True)),
                ('who4', models.CharField(blank=True, max_length=8, null=True)),
                ('who4_2', models.CharField(blank=True, max_length=9, null=True)),
                ('who5', models.CharField(blank=True, max_length=8, null=True)),
                ('who5_2', models.CharField(blank=True, max_length=9, null=True)),
                ('who8', models.CharField(blank=True, max_length=19, null=True)),
                ('who8_1', models.CharField(blank=True, max_length=8, null=True)),
                ('who8_2', models.CharField(blank=True, max_length=9, null=True)),
                ('customer_product_status', models.CharField(blank=True, choices=[('Returned Empty to QwikPartner', 'Returned Empty to QwikPartner'), ('Received Filled', 'Received Filled')], max_length=35, null=True, verbose_name="QwikCustomer's Remark")),
                ('admin_product_status', models.CharField(blank=True, choices=[('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Returned Empty to QwikLet', 'Returned Empty to QwikLet'), ('Dispatched to Plant', 'Dispatched to Plant'), ('Delivered Filled to QwikLet', 'Delivered Filled to QwikLet'), ('Dispatched Filled to QwikCustomer', 'Dispatched Filled to QwikCustomer'), ('Delivered to QwikCustomer', 'Delivered to QwikCustomer'), ('Returned Filled to QwikLet', 'Returned Filled to QwikLet')], max_length=35, null=True, verbose_name="QwikAdmin's Remark")),
                ('admin_product', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Owing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder', models.CharField(max_length=110, null=True, verbose_name='Cylinder Id')),
                ('category', models.CharField(max_length=12, null=True)),
                ('outlet', models.CharField(max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Id', models.CharField(max_length=20, null=True, unique=True, verbose_name='Cylinder Id')),
                ('available', models.BooleanField(default=False, max_length=5)),
                ('vendor_product_status', models.CharField(choices=[('Dispatched to Plant', 'Dispatched to Plant'), ('Released Filled to QwikPartner', 'Released Filled to QwikPartner'), ('Dispatched Empty', 'Dispatched Empty'), ('Received Empty', 'Received Empty'), ('Dispatched Filled', 'Dispatched Filled'), ('Received Filled', 'Received Filled')], max_length=30, null=True, verbose_name="QwikVendor's Remark")),
                ('vendor_product', models.CharField(blank=True, max_length=20, null=True)),
                ('vendor_consent', models.BooleanField(default=False, max_length=5)),
                ('partner_product_status', models.CharField(blank=True, choices=[('Received Empty from QwikCustomer', 'Received Empty from QwikCustomer'), ('Returned Empty', 'Returned Empty'), ('Received Empty', 'Received Empty'), ('Received Filled', 'Received Filled'), ('Selected', 'Selected'), ('Unselected', 'Unselected')], default='Unselected', max_length=35, null=True, verbose_name="QwikPartner's Remark")),
                ('partner_product', models.CharField(blank=True, max_length=20, null=True)),
                ('partner_consent', models.BooleanField(default=False, max_length=5)),
                ('batch_Id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_category', to='products.category', verbose_name='Product')),
            ],
            options={
                'ordering': ('product_Id',),
            },
        ),
    ]
