# Generated by Django 3.2.4 on 2022-05-02 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.outlet'),
        ),
        migrations.AddField(
            model_name='owing',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id',)},
        ),
        migrations.AlterIndexTogether(
            name='owing',
            index_together={('id',)},
        ),
        migrations.AlterIndexTogether(
            name='cylinder',
            index_together={('id',)},
        ),
    ]
